# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(314, 198)
        Login.setStyleSheet("QPushButton {\n"
"       color: #212121; \n"
"        border-radius: 10px; \n"
"        border: 1px groove gray;\n"
"        background-color: #F5F7FA\n"
"}\n"
"\n"
" QPushButton:hover {\n"
"        background-color: #d9d9f3 ;\n"
" }")
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.user_name_input = QtWidgets.QLineEdit(Login)
        self.user_name_input.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.user_name_input.setFont(font)
        self.user_name_input.setObjectName("user_name_input")
        self.horizontalLayout.addWidget(self.user_name_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pwd_input = QtWidgets.QLineEdit(Login)
        self.pwd_input.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.pwd_input.setFont(font)
        self.pwd_input.setText("")
        self.pwd_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_input.setObjectName("pwd_input")
        self.horizontalLayout_2.addWidget(self.pwd_input)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stu_btn = QtWidgets.QRadioButton(Login)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.stu_btn.setFont(font)
        self.stu_btn.setObjectName("stu_btn")
        self.horizontalLayout_3.addWidget(self.stu_btn)
        self.admin_btn = QtWidgets.QRadioButton(Login)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.admin_btn.setFont(font)
        self.admin_btn.setObjectName("admin_btn")
        self.horizontalLayout_3.addWidget(self.admin_btn)
        self.teacher_btn = QtWidgets.QRadioButton(Login)
        self.teacher_btn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.teacher_btn.setFont(font)
        self.teacher_btn.setObjectName("teacher_btn")
        self.horizontalLayout_3.addWidget(self.teacher_btn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.login_btn = QtWidgets.QPushButton(Login)
        self.login_btn.setMinimumSize(QtCore.QSize(130, 40))
        self.login_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "登录"))
        self.label.setText(_translate("Login", "工号："))
        self.label_2.setText(_translate("Login", "密码："))
        self.stu_btn.setText(_translate("Login", "学生"))
        self.admin_btn.setText(_translate("Login", "管理员"))
        self.teacher_btn.setText(_translate("Login", "教师"))
        self.login_btn.setText(_translate("Login", "登录"))
